image: node:18.17.1

stages:
    - deploy

deploy:
    stage: deploy
    script:
        - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
        - npm install
        - npm run prepare
        - npm publish
        - echo "-- build completed successfully"
    only:
        - main
